// Supabase Edge Function: Asaas webhook. This is the ONLY source of truth for whether an
// appointment/subscription was actually paid — never trust the client-side redirect (successUrl),
// it can be skipped, replayed, or spoofed. Unlike Mercado Pago's IPN (which only sends an id and
// requires fetching the real object back from their API), Asaas POSTs the full payment/subscription
// object directly — authenticity instead comes from the `asaas-access-token` header, a shared
// secret configured when the webhook was registered in the Asaas dashboard (Integrações > Webhooks),
// distinct from the API key itself. Never skip that check.
//
// Deploy: supabase functions deploy asaas-webhook --no-verify-jwt
// (--no-verify-jwt is required: Asaas calls this without a Supabase auth token)
// Secrets: supabase secrets set ASAAS_WEBHOOK_TOKEN=... (set the same value when creating the
// webhook in the Asaas dashboard/API — see https://docs.asaas.com/docs/criar-novo-webhook-pela-aplicacao-web)
import { createClient } from "npm:@supabase/supabase-js@2";
import { asaasFetch } from "../_shared/asaasClient.ts";
import { sendBookingConfirmationEmail } from "../_shared/email.ts";

const PLATFORM_FEE_RATE = 0.1;

function classifyPaymentStatus(asaasStatus: string): "paid" | "refunded" | "pending" | null {
  if (["RECEIVED", "CONFIRMED", "RECEIVED_IN_CASH"].includes(asaasStatus)) return "paid";
  if (["REFUNDED", "REFUND_REQUESTED", "CHARGEBACK_REQUESTED", "CHARGEBACK_DISPUTE"].includes(asaasStatus)) return "refunded";
  if (["PENDING", "OVERDUE", "AWAITING_RISK_ANALYSIS"].includes(asaasStatus)) return "pending";
  // DELETED and anything unrecognized: nothing to record.
  return null;
}

/** Professional-subscription branch (create-asaas-subscription): a payment generated by a
 *  subscription carries `payment.subscription` (the Asaas subscription id) instead of our own
 *  externalReference, so it's routed here before the generic appointment-payment handling below
 *  ever sees it. Only the base active/cancelled/pending states are tracked; per-cycle payment rows
 *  aren't recorded for subscriptions (out of scope for now, same "ship the real mechanism, flag
 *  what's deferred" posture as the placeholder plan price). */
async function handleSubscriptionPayment(
  asaasSubscriptionId: string,
  paymentStatus: "paid" | "refunded" | "pending",
  apiKey: string,
  supabase: ReturnType<typeof createClient>
): Promise<Response> {
  const { data: subscriptionRow } = await supabase
    .from("professional_subscriptions")
    .select("id")
    .eq("asaas_subscription_id", asaasSubscriptionId)
    .maybeSingle();
  if (!subscriptionRow) return new Response(JSON.stringify({ ignored: true }), { status: 200 });

  const status = paymentStatus === "paid" ? "active" : paymentStatus === "refunded" ? "cancelled" : "pending";

  let currentPeriodEnd: string | null = null;
  if (status === "active") {
    const subResponse = await asaasFetch(`/subscriptions/${asaasSubscriptionId}`, apiKey);
    if (subResponse.ok) {
      const sub = await subResponse.json();
      currentPeriodEnd = sub.nextDueDate ? new Date(sub.nextDueDate).toISOString() : null;
    }
  }

  const { error } = await supabase
    .from("professional_subscriptions")
    .update({ status, current_period_end: currentPeriodEnd, updated_at: new Date().toISOString() })
    .eq("id", subscriptionRow.id);

  if (error) return new Response(JSON.stringify({ error: error.message }), { status: 500 });
  return new Response(JSON.stringify({ ok: true }), { status: 200 });
}

async function handleSubscriptionLifecycleEvent(event: string, asaasSubscriptionId: string, supabase: ReturnType<typeof createClient>): Promise<Response> {
  if (event !== "SUBSCRIPTION_INACTIVATED" && event !== "SUBSCRIPTION_DELETED") {
    return new Response(JSON.stringify({ ignored: true }), { status: 200 });
  }

  const { error } = await supabase
    .from("professional_subscriptions")
    .update({ status: "cancelled", updated_at: new Date().toISOString() })
    .eq("asaas_subscription_id", asaasSubscriptionId);

  if (error) return new Response(JSON.stringify({ error: error.message }), { status: 500 });
  return new Response(JSON.stringify({ ok: true }), { status: 200 });
}

Deno.serve(async req => {
  try {
    const webhookToken = Deno.env.get("ASAAS_WEBHOOK_TOKEN");
    if (!webhookToken) return new Response(JSON.stringify({ error: "ASAAS_WEBHOOK_TOKEN não configurado." }), { status: 500 });
    if (req.headers.get("asaas-access-token") !== webhookToken) {
      return new Response(JSON.stringify({ error: "Token inválido." }), { status: 401 });
    }

    const apiKey = Deno.env.get("ASAAS_API_KEY");
    if (!apiKey) return new Response(JSON.stringify({ error: "ASAAS_API_KEY não configurado." }), { status: 500 });

    const body = await req.json();
    const event: string = body.event ?? "";
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

    if (event.startsWith("SUBSCRIPTION_")) {
      const asaasSubscriptionId = body.subscription?.id;
      if (!asaasSubscriptionId) return new Response(JSON.stringify({ ignored: true }), { status: 200 });
      return handleSubscriptionLifecycleEvent(event, asaasSubscriptionId, supabase);
    }

    if (!event.startsWith("PAYMENT_")) return new Response(JSON.stringify({ ignored: true }), { status: 200 });

    const payment = body.payment;
    if (!payment?.id) return new Response(JSON.stringify({ ignored: true }), { status: 200 });

    const status = classifyPaymentStatus(payment.status ?? "");
    if (!status) return new Response(JSON.stringify({ ignored: true, asaasStatus: payment.status }), { status: 200 });

    if (payment.subscription) {
      return handleSubscriptionPayment(payment.subscription, status, apiKey, supabase);
    }

    const appointmentId: string | undefined = payment.externalReference;
    if (!appointmentId) return new Response(JSON.stringify({ ignored: true }), { status: 200 });

    // amount is whatever Asaas actually charged/received — with "repassar taxa ao paciente" on,
    // that already includes the commission surcharge (create-asaas-preference/create-asaas-pix-charge).
    // The commission itself is always computed off the appointment's own base price, never off the
    // charged total, so what the professional nets (amount - platform_fee) stays the session price
    // either way — only who paid the extra 10% changes.
    const amount = Number(payment.value ?? 0);
    const { data: appointmentRow } = await supabase.from("appointments").select("price").eq("id", appointmentId).maybeSingle();
    const basePrice = Number(appointmentRow?.price ?? amount);
    const platformFee = Number((basePrice * PLATFORM_FEE_RATE).toFixed(2));

    const { data: existingPayment } = await supabase
      .from("payments")
      .select("status")
      .eq("provider_payment_id", String(payment.id))
      .maybeSingle();
    const alreadyPaid = existingPayment?.status === "paid";

    const { error } = await supabase.from("payments").upsert(
      {
        appointment_id: appointmentId,
        status,
        method: (payment.billingType ?? "asaas").toLowerCase(),
        amount,
        platform_fee: platformFee,
        provider: "asaas",
        provider_payment_id: String(payment.id),
      },
      { onConflict: "provider_payment_id" }
    );

    if (error) return new Response(JSON.stringify({ error: error.message }), { status: 500 });

    // Best-effort, and only on the first time this payment is recorded as paid (avoids duplicate
    // e-mails when Asaas redelivers the same notification).
    if (status === "paid" && !alreadyPaid) {
      await sendBookingConfirmationEmail(supabase, appointmentId).catch(() => {});
    }

    return new Response(JSON.stringify({ ok: true }), { status: 200 });
  } catch (error) {
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Erro desconhecido." }), { status: 500 });
  }
});
